server:
  port: 8060
spring:
  datasource:
      password: root
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/huangdemo?characterEncoding=utf-8&&useSSL=false&allowMultiQueries=true
      name: localhost_3306
  cache:
     ehcache:
       config: classpath:cache/ehcache.xml
     type: ehcache
  redis:
      host: 127.0.0.1
      database: 0
      port: 6379
      password:
      jedis:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 0
        timeout: 1000
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      serialization:
         WRITE_DATES_AS_TIMESTAMPS: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
      org:
        mybatis: debug
